apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  labels: {{ include "app.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.app.replicaCount | default 1 }}
  selector:
    matchLabels: {{ include "app.selectorLabels" (dict "role" "app" "context" .) | nindent 6 }}-deployment
  template:
    metadata:
      labels: {{ include "app.selectorLabels" (dict "role" "app" "context" .) | nindent 8 }}-deployment
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
          env:
            {{- if .Values.app.dbHostname }}
            - name: {{ .Values.app.dbHostname }}
              value: {{ include "app.dbHeadlessServiceName" . }}
            {{- end }}
            {{- if .Values.app.env }}
            {{- range .Values.app.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          {{- if .Values.app.envFromSecrets.enabled }}
          envFrom:
            {{- range .Values.app.envFromSecrets.secretRefNames }}
            - secretRef:
                name: {{ . | quote }}
            {{- end }}
          {{- end }}
          volumeMounts:
            {{- $claimName := .Values.existingClaim | default .Values.persistence.name }}
            {{- if $claimName }}
            {{- range .Values.app.volumeMounts }}
            - name: {{ $claimName }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            {{- end }}
          {{- if .Values.app.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 5
          {{- end }}
          {{- if .Values.app.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command: {{ toJson .Values.app.livenessProbe.command }}
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
          {{- end }}
      volumes:
        {{- $claimName := .Values.existingClaim | default .Values.persistence.name }}
        {{- if $claimName }}
        - name: {{ $claimName }}
          persistentVolumeClaim:
            claimName: {{ $claimName }}
        {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
