apiVersion: v2
name: stateless-app
description: A generic Helm chart for deploying stateless web applications.
type: application
version: 0.1.0
appVersion: "1.0"

# maintainers:
#   - name:
#     email:
# keywords:
#   - stateless
#   - web
#   - api
#   - kubernetes
#   - helm
# sources:
#   - https://github.com/etc

# annotations:
#   category: "stateless-services"

dependencies:
  - name: nfspersistence
    version: 0.3.1
    repository: https://tinycloud-labs.github.io/helm/
