name: Terragrunt HCL Format

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - "terraform/live/**"
      - "terraform/catalog/units/**"

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: shakir85/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/setup-git
        with:
          repo-path: /__w/homelab/homelab

      - run: |
          git fetch origin ${{ github.head_ref }}
          git pull origin ${{ github.head_ref }}

      - name: Format HCL files
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_dir: 'terraform/live'
          tg_command: 'hcl fmt'

      - name: Commit changes
        run: |
          git add -A
          git commit -m "ðŸ¤– chore: Terragrunt HCL lint [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
